# Generated by Django 4.1.7 on 2023-03-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaeges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaeges_name', models.CharField(max_length=20)),
                ('service', models.TextField()),
                ('packaeges_price', models.PositiveIntegerField()),
                ('packaeges_offer', models.CharField(max_length=20)),
            ],
        ),
    ]
