# Generated by Django 4.1.7 on 2023-04-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_packaeges_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chekout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('society', models.TextField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=50)),
                ('gst', models.CharField(max_length=20)),
            ],
        ),
    ]
