# Generated by Django 4.1.7 on 2023-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chekout_landmark_chekout_pcode_alter_chekout_society'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_duration', models.CharField(max_length=20)),
                ('course_trainer', models.CharField(max_length=20)),
                ('course_about', models.CharField(max_length=20)),
            ],
        ),
    ]
