# Generated by Django 4.1.7 on 2023-04-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_academy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='course_about',
            field=models.CharField(max_length=50),
        ),
    ]
