# Generated by Django 4.1.7 on 2023-04-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_academy_course_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('certificate_no', models.CharField(max_length=20)),
            ],
        ),
    ]
