# Generated by Django 4.1.7 on 2023-04-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_no',
        ),
    ]
