# Generated by Django 4.1.7 on 2023-04-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_certificate_certificate_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=123, upload_to='profile'),
            preserve_default=False,
        ),
    ]
