# Generated by Django 4.1.7 on 2023-04-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
