# Generated by Django 4.1.7 on 2023-04-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
